name: package

on:
  push:
    tags:
      - "v*.*.*"
  workflow_dispatch:

jobs:
  packages:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Setup Registry
        run: |
          echo "@mystikonetwork:registry=https://npm.pkg.github.com" >> $HOME/.npmrc
          echo "//npm.pkg.github.com/:_authToken=${{ secrets.XZK_STAKING_PACKAGE_TOKEN }}" >> $HOME/.npmrc

      - name: Install Dependencies
        run: yarn install

      - name: Build
        run: yarn build

      - name: Publish ABI Package
        run: |
          cd packages/abi
          yarn publish --yes

      - name: Publish API Package
        run: |
          cd packages/api
          yarn publish --yes

      # - name: Telegram Failure Notification
      #   uses: appleboy/telegram-action@master
      #   if: failure()
      #   with:
      #     message: ❗ Build failed for [${{ github.repository }}](https://github.com/${{ github.repository }}/actions) because of ${{ github.actor }}
      #     format: markdown
      #     to: ${{ secrets.TELEGRAM_CHAT_ID }}
      #     token: ${{ secrets.TELEGRAM_BOT_TOKEN }}
